name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        gcc-version: '11'  # Specify the GCC version you need

    - name: Build
      run: |
        g++ -o my_program main.cpp

    - name: Run
      run: |
        ./my_program
